extends RefCounted

const FONT_PRIMARY := "res://fonts/Atkinson_Hyperlegible/AtkinsonHyperlegible-Regular.ttf"
const FONT_NARROW := "res://fonts/Atkinson_Hyperlegible/AtkinsonHyperlegible-Bold.ttf"
const FONT_DISPLAY := "res://fonts/Fredoka/static/Fredoka-Bold.ttf"
const FONT_BUTTON := "res://fonts/Fredoka/static/Fredoka-SemiBold.ttf"

const BTN_PRIMARY := "res://assets/UI/kenney_adventure/button_brown.png"
const BTN_SECONDARY := "res://assets/UI/kenney_adventure/button_grey.png"
const BTN_DANGER := "res://assets/UI/kenney_adventure/button_red.png"
const BTN_ROUND := "res://assets/UI/kenney_adventure/round_brown.png"
const BTN_ROUND_DARK := "res://assets/UI/kenney_adventure/round_brown_dark.png"
const PANEL := "res://assets/UI/kenney_adventure/panel_brown.png"
const PANEL_DARK := "res://assets/UI/kenney_adventure/panel_brown_dark.png"
const BANNER := "res://assets/UI/kenney_adventure/banner_modern.png"
const PROGRESS_GREEN := "res://assets/UI/kenney_adventure/progress_green.png"
const PROGRESS_RED := "res://assets/UI/kenney_adventure/progress_red.png"
const PROGRESS_WHITE := "res://assets/UI/kenney_adventure/progress_white.png"

const CYBER_BTN_PRIMARY := "res://assets/UI/cyberprank/space_expansion/blue/button_square_header_large_rectangle_screws.png"
const CYBER_BTN_SECONDARY := "res://assets/UI/cyberprank/space_expansion/blue/button_square_header_notch_rectangle_screws.png"
const CYBER_BTN_DANGER := "res://assets/UI/cyberprank/space_expansion/extra/button_rectangle_depth.png"
const CYBER_BTN_ROUND := "res://assets/UI/cyberprank/space_expansion/blue/button_square_header_large_square_screws.png"
const CYBER_BTN_ROUND_DARK := "res://assets/UI/cyberprank/space_expansion/blue/button_square_header_blade_square_screws.png"
const CYBER_PANEL := "res://assets/UI/cyberprank/space_expansion/extra/panel_rectangle_screws.png"
const CYBER_PANEL_DARK := "res://assets/UI/cyberprank/space_expansion/extra/panel_glass_screws.png"
const CYBER_BANNER := "res://assets/UI/cyberprank/space_expansion/blue/button_square_header_blade_rectangle_screws.png"
const CYBER_PROGRESS_FILL := "res://assets/UI/cyberprank/space_expansion/blue/bar_round_gloss_large.png"
const CYBER_PROGRESS_ALERT := "res://assets/UI/cyberprank/space_expansion/blue/bar_square_gloss_large.png"
const CYBER_PROGRESS_BACK := "res://assets/UI/cyberprank/space_expansion/extra/bar_shadow_round_outline_large.png"

const ICON_PLAY := "res://assets/UI/Icons/icon_play_light.png"
const ICON_PAUSE := "res://assets/UI/Icons/pause.png"
const ICON_HOME := "res://assets/UI/Icons/home.png"
const ICON_GEAR := "res://assets/UI/Icons/gear.png"
const ICON_TROPHY := "res://assets/UI/Icons/trophy.png"
const ICON_CROSS := "res://assets/UI/Icons/icon_cross.png"
const ICON_CHECK := "res://assets/UI/Icons/icon_checkmark.png"
const ICON_AUDIO_ON := "res://assets/UI/Icons/audioOn.png"
const ICON_AUDIO_OFF := "res://assets/UI/Icons/audioOff.png"
const ICON_MUSIC_ON := "res://assets/UI/Icons/musicOn.png"
const ICON_MUSIC_OFF := "res://assets/UI/Icons/musicOff.png"
const ICON_COIN := "res://assets/UI/kenney_adventure/minimap_icon_jewel_yellow.png"
const ICON_STAR := "res://assets/UI/kenney_adventure/minimap_icon_star_yellow.png"
const ICON_WARNING := "res://assets/UI/kenney_adventure/minimap_icon_exclamation_yellow.png"
